const NOTIFICATION_TYPE_STAKING = 'staking';
const NOTIFICATION_TYPE_WITHDRAWAL = 'withdrawal';
const NOTIFICATION_TYPE_MINING = 'mining';
const NOTIFICATION_TYPE_SUBSCRIPTION = 'subscription';
const NOTIFICATION_TYPE_REFERRAL = 'referral';
const NOTIFICATION_TYPE_PROMOTION = 'promotion';
const NOTIFICATION_TYPE_OTHER = 'other';

export { NOTIFICATION_TYPE_STAKING, NOTIFICATION_TYPE_WITHDRAWAL, NOTIFICATION_TYPE_MINING, NOTIFICATION_TYPE_SUBSCRIPTION, NOTIFICATION_TYPE_REFERRAL, NOTIFICATION_TYPE_PROMOTION, NOTIFICATION_TYPE_OTHER };